import { gunzipSync } from "node:zlib";
import { Command } from "commander";
import { SchedulePayload } from "schedule/src/proto/cli.ts";

function decodePayload(raw: string): SchedulePayload {
  // Strip whitespace the user may have accidentally included.
  const stripped = raw.trim().replace(/\s+/g, "");

  // base64url → Buffer
  const buf = Buffer.from(stripped, "base64url");

  // Attempt gzip decompression; fall back to raw bytes if not compressed.
  let bytes: Uint8Array;
  try {
    bytes = gunzipSync(buf);
  } catch {
    bytes = buf;
  }

  return SchedulePayload.decode(bytes);
}

export const runCommand = new Command("run")
  .description("Execute a schedule payload generated by the uoplan web app")
  .argument("<payload>", "Base64url-encoded (optionally gzipped) protobuf payload")
  .action((payload: string) => {
    let decoded: SchedulePayload;
    try {
      decoded = decodePayload(payload);
    } catch {
      console.error("Invalid payload: could not decode. Make sure you copied it correctly.");
      process.exit(1);
    }

    // Placeholder — will eventually add courses to cart and optionally check out.
    console.log(`Term: ${decoded.termId}`);
    for (const course of decoded.courses) {
      const sections = course.sections.map((s) => `${s.component} ${s.section}`).join(", ");
      console.log(`  ${course.courseCode}  ${sections}`);
    }
  });
