import { defineConfig } from "oxfmt";

export default defineConfig({
  ignorePatterns: [
    "apps/scraper/data/**",
    "**/__fixtures__/**",
    "**/*.gen.ts",
    // Lingui-compiled message catalogs (minified, generated by `lingui compile`).
    "packages/i18n/src/locales/**/messages.ts",
    "CHANGELOG.md",
  ],
});
