import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef } from "react";
import { motion } from "framer-motion";
import { CalendarPage } from "../../../components/calendar/CalendarPage";
import { navigateToWizardStep } from "../../../lib/appNavigation";
import { WizardStep } from "../../../lib/wizardSteps";
import { useRepairSeedOnCalendarMount } from "../../../hooks/useRepairSeedOnCalendarMount";
import { useAppStore } from "../../../store/appStore";

export const Route = createFileRoute("/schedule/calendar/advanced")({
  component: AdvancedCalendarRoute,
});

function AdvancedCalendarRoute() {
  useRepairSeedOnCalendarMount();

  const generateSchedules = useAppStore((s) => s.generateSchedules);
  const indices = useAppStore((s) => s.indices);
  const currentSchedule = useAppStore((s) => s.currentSchedule);
  const firstSeed = useAppStore((s) => s.firstSeed);

  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (hasAutoGeneratedRef.current || !indices) return;
    if (currentSchedule === null && firstSeed > 0) {
      hasAutoGeneratedRef.current = true;
      void generateSchedules();
    }
  }, [indices, currentSchedule, firstSeed, generateSchedules]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{ duration: 0.3 }}
      style={{ width: "100%", minHeight: "100vh" }}
    >
      <CalendarPage variant="advanced" onBack={() => navigateToWizardStep(WizardStep.Generate)} />
    </motion.div>
  );
}
