import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef } from "react";
import { CalendarPage } from "../../../components/calendar/CalendarPage";
import { useRepairSeedOnCalendarMount } from "../../../hooks/useRepairSeedOnCalendarMount";
import { navigateToWizardStep } from "../../../lib/appNavigation";
import { WizardStep } from "../../../lib/wizardSteps";
import { useAppStore } from "../../../store/appStore";

export const Route = createFileRoute("/schedule/calendar/basic")({
  component: BasicCalendarRoute,
});

function BasicCalendarRoute() {
  useRepairSeedOnCalendarMount();

  const generateSchedules = useAppStore((s) => s.generateSchedules);
  const indices = useAppStore((s) => s.indices);
  const currentSchedule = useAppStore((s) => s.currentSchedule);
  const firstSeed = useAppStore((s) => s.firstSeed);

  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (hasAutoGeneratedRef.current || !indices) return;
    if (currentSchedule === null && firstSeed > 0) {
      hasAutoGeneratedRef.current = true;
      void generateSchedules();
    }
  }, [indices, currentSchedule, firstSeed, generateSchedules]);

  return <CalendarPage variant="basic" onBack={() => navigateToWizardStep(WizardStep.Mode)} />;
}
