import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef } from "react";
import { CalendarPage } from "../../../components/calendar/CalendarPage";
import { AppDataLoader } from "../../../components/shared/AppDataLoader";
import { useRepairSeedOnCalendarMount } from "../../../hooks/useRepairSeedOnCalendarMount";
import { useAppStore } from "../../../store/appStore";
import { buildTabTitle } from "../../../lib/seo";
import { formatTermLabel } from "../../../lib/term/termLabel";

export const Route = createFileRoute("/schedule/calendar/")({
  head: () => buildTabTitle("Your schedule"),
  component: CalendarRoute,
});

function CalendarRoute() {
  useRepairSeedOnCalendarMount();

  const generateSchedules = useAppStore((s) => s.generateSchedules);
  const generateBasicSchedules = useAppStore((s) => s.generateBasicSchedules);
  const program = useAppStore((s) => s.program);
  const indices = useAppStore((s) => s.indices);
  const currentSchedule = useAppStore((s) => s.currentSchedule);
  const firstSeed = useAppStore((s) => s.firstSeed);
  const terms = useAppStore((s) => s.terms);
  const selectedTermId = useAppStore((s) => s.selectedTermId);
  const loadProgress = useAppStore((s) => s.loadProgress);

  useEffect(() => {
    const hasTerm = terms?.some((t) => String(t.termId) === selectedTermId) ?? false;
    const termName = hasTerm && selectedTermId ? formatTermLabel(selectedTermId) : null;
    document.title = termName ? `${termName} schedule` : "Your schedule";
  }, [terms, selectedTermId]);

  const generationError = useAppStore((s) => s.generationError);

  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (hasAutoGeneratedRef.current || !indices) return;
    // A generation has already been attempted by another path (it produced an
    // error). Mark as attempted so dismissing the error modal doesn't re-trigger
    // generation and reopen the modal.
    if (generationError !== null) {
      hasAutoGeneratedRef.current = true;
      return;
    }
    if (currentSchedule === null && firstSeed > 0) {
      hasAutoGeneratedRef.current = true;
      // Basic mode (no program selected) must use the basic-elective generation
      // path; the advanced path has no requirement courses and would error out.
      void (program === null ? generateBasicSchedules() : generateSchedules());
    }
  }, [
    indices,
    currentSchedule,
    firstSeed,
    generateSchedules,
    generateBasicSchedules,
    program,
    generationError,
  ]);

  // Keep the data loader on screen until the very first schedule resolves, so the
  // calendar doesn't flash an empty state during the initial auto-generation.
  const firstScheduleResolved = currentSchedule !== null || generationError !== null;
  const initialLoadResolvedRef = useRef(false);
  useEffect(() => {
    if (firstScheduleResolved) initialLoadResolvedRef.current = true;
  }, [firstScheduleResolved]);

  const awaitingFirstSchedule =
    !firstScheduleResolved && !initialLoadResolvedRef.current && indices != null && firstSeed > 0;

  if (awaitingFirstSchedule) {
    return <AppDataLoader progress={loadProgress} />;
  }

  return <CalendarPage />;
}
