import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef } from "react";
import { CalendarPage } from "../../../components/calendar/CalendarPage";
import { useRepairSeedOnCalendarMount } from "../../../hooks/useRepairSeedOnCalendarMount";
import { useAppStore } from "../../../store/appStore";
import { buildTabTitle } from "../../../lib/seo";

export const Route = createFileRoute("/schedule/calendar/")({
  head: () => buildTabTitle("Your schedule"),
  component: CalendarRoute,
});

function CalendarRoute() {
  useRepairSeedOnCalendarMount();

  const generateSchedules = useAppStore((s) => s.generateSchedules);
  const indices = useAppStore((s) => s.indices);
  const currentSchedule = useAppStore((s) => s.currentSchedule);
  const firstSeed = useAppStore((s) => s.firstSeed);
  const terms = useAppStore((s) => s.terms);
  const selectedTermId = useAppStore((s) => s.selectedTermId);

  useEffect(() => {
    const termName = terms?.find((t) => String(t.termId) === selectedTermId)?.name;
    document.title = termName ? `${termName} schedule` : "Your schedule";
  }, [terms, selectedTermId]);

  const generationError = useAppStore((s) => s.generationError);

  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (hasAutoGeneratedRef.current || !indices) return;
    // A generation has already been attempted by another path (it produced an
    // error). Mark as attempted so dismissing the error modal doesn't re-trigger
    // generation and reopen the modal.
    if (generationError !== null) {
      hasAutoGeneratedRef.current = true;
      return;
    }
    if (currentSchedule === null && firstSeed > 0) {
      hasAutoGeneratedRef.current = true;
      void generateSchedules();
    }
  }, [indices, currentSchedule, firstSeed, generateSchedules, generationError]);

  return <CalendarPage />;
}
