import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef } from "react";
import { CalendarPage } from "../../../components/calendar/CalendarPage";
import { useRepairSeedOnCalendarMount } from "../../../hooks/useRepairSeedOnCalendarMount";
import { useAppStore } from "../../../store/appStore";
import { buildTabTitle } from "../../../lib/seo";

export const Route = createFileRoute("/schedule/calendar/")({
  head: () => buildTabTitle("Your schedule"),
  component: CalendarRoute,
});

function CalendarRoute() {
  useRepairSeedOnCalendarMount();

  const generateSchedules = useAppStore((s) => s.generateSchedules);
  const indices = useAppStore((s) => s.indices);
  const currentSchedule = useAppStore((s) => s.currentSchedule);
  const firstSeed = useAppStore((s) => s.firstSeed);
  const program = useAppStore((s) => s.program);
  const terms = useAppStore((s) => s.terms);
  const selectedTermId = useAppStore((s) => s.selectedTermId);

  useEffect(() => {
    const termName = terms?.find((t) => String(t.termId) === selectedTermId)?.name;
    document.title = termName ? `${termName} schedule` : "Your schedule";
  }, [terms, selectedTermId]);

  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (hasAutoGeneratedRef.current || !indices) return;
    // Auto-generate for the basic (skip) path only — full-wizard path opens the options modal
    if (program === null && currentSchedule === null && firstSeed > 0) {
      hasAutoGeneratedRef.current = true;
      void generateSchedules();
    }
  }, [indices, currentSchedule, firstSeed, generateSchedules, program]);

  return <CalendarPage />;
}
