/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StepStepSlugRouteImport } from './routes/step/$stepSlug'
import { Route as CalendarBasicRouteImport } from './routes/calendar/basic'
import { Route as CalendarAdvancedRouteImport } from './routes/calendar/advanced'

const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StepStepSlugRoute = StepStepSlugRouteImport.update({
  id: '/step/$stepSlug',
  path: '/step/$stepSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarBasicRoute = CalendarBasicRouteImport.update({
  id: '/calendar/basic',
  path: '/calendar/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarAdvancedRoute = CalendarAdvancedRouteImport.update({
  id: '/calendar/advanced',
  path: '/calendar/advanced',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/calendar/advanced': typeof CalendarAdvancedRoute
  '/calendar/basic': typeof CalendarBasicRoute
  '/step/$stepSlug': typeof StepStepSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/calendar/advanced': typeof CalendarAdvancedRoute
  '/calendar/basic': typeof CalendarBasicRoute
  '/step/$stepSlug': typeof StepStepSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/calendar/advanced': typeof CalendarAdvancedRoute
  '/calendar/basic': typeof CalendarBasicRoute
  '/step/$stepSlug': typeof StepStepSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/calendar/advanced'
    | '/calendar/basic'
    | '/step/$stepSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/calendar/advanced'
    | '/calendar/basic'
    | '/step/$stepSlug'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/calendar/advanced'
    | '/calendar/basic'
    | '/step/$stepSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  CalendarAdvancedRoute: typeof CalendarAdvancedRoute
  CalendarBasicRoute: typeof CalendarBasicRoute
  StepStepSlugRoute: typeof StepStepSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step/$stepSlug': {
      id: '/step/$stepSlug'
      path: '/step/$stepSlug'
      fullPath: '/step/$stepSlug'
      preLoaderRoute: typeof StepStepSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/basic': {
      id: '/calendar/basic'
      path: '/calendar/basic'
      fullPath: '/calendar/basic'
      preLoaderRoute: typeof CalendarBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/advanced': {
      id: '/calendar/advanced'
      path: '/calendar/advanced'
      fullPath: '/calendar/advanced'
      preLoaderRoute: typeof CalendarAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  CalendarAdvancedRoute: CalendarAdvancedRoute,
  CalendarBasicRoute: CalendarBasicRoute,
  StepStepSlugRoute: StepStepSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
