/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ScheduleRouteRouteImport } from './routes/schedule/route'
import { Route as ExploreRouteRouteImport } from './routes/explore/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ScheduleStepTermRouteImport } from './routes/schedule/step/term'
import { Route as ScheduleStepProgramRouteImport } from './routes/schedule/step/program'
import { Route as ScheduleStepOptionsRouteImport } from './routes/schedule/step/options'
import { Route as ScheduleStepModeRouteImport } from './routes/schedule/step/mode'
import { Route as ScheduleStepGenerateRouteImport } from './routes/schedule/step/generate'
import { Route as ScheduleStepCompletedRouteImport } from './routes/schedule/step/completed'
import { Route as ScheduleStepAssignRouteImport } from './routes/schedule/step/assign'
import { Route as ScheduleCalendarBasicRouteImport } from './routes/schedule/calendar/basic'
import { Route as ScheduleCalendarAdvancedRouteImport } from './routes/schedule/calendar/advanced'
import { Route as ExploreProfessorLegacyIdRouteImport } from './routes/explore/professor/$legacyId'
import { Route as ExploreDisciplineDisciplineRouteImport } from './routes/explore/discipline/$discipline'
import { Route as ExploreCourseCourseRouteImport } from './routes/explore/course/$course'

const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRouteRoute = ScheduleRouteRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRouteRoute = ExploreRouteRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRouteRoute,
} as any)
const ScheduleStepTermRoute = ScheduleStepTermRouteImport.update({
  id: '/step/term',
  path: '/step/term',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleStepProgramRoute = ScheduleStepProgramRouteImport.update({
  id: '/step/program',
  path: '/step/program',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleStepOptionsRoute = ScheduleStepOptionsRouteImport.update({
  id: '/step/options',
  path: '/step/options',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleStepModeRoute = ScheduleStepModeRouteImport.update({
  id: '/step/mode',
  path: '/step/mode',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleStepGenerateRoute = ScheduleStepGenerateRouteImport.update({
  id: '/step/generate',
  path: '/step/generate',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleStepCompletedRoute = ScheduleStepCompletedRouteImport.update({
  id: '/step/completed',
  path: '/step/completed',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleStepAssignRoute = ScheduleStepAssignRouteImport.update({
  id: '/step/assign',
  path: '/step/assign',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleCalendarBasicRoute = ScheduleCalendarBasicRouteImport.update({
  id: '/calendar/basic',
  path: '/calendar/basic',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const ScheduleCalendarAdvancedRoute =
  ScheduleCalendarAdvancedRouteImport.update({
    id: '/calendar/advanced',
    path: '/calendar/advanced',
    getParentRoute: () => ScheduleRouteRoute,
  } as any)
const ExploreProfessorLegacyIdRoute =
  ExploreProfessorLegacyIdRouteImport.update({
    id: '/professor/$legacyId',
    path: '/professor/$legacyId',
    getParentRoute: () => ExploreRouteRoute,
  } as any)
const ExploreDisciplineDisciplineRoute =
  ExploreDisciplineDisciplineRouteImport.update({
    id: '/discipline/$discipline',
    path: '/discipline/$discipline',
    getParentRoute: () => ExploreRouteRoute,
  } as any)
const ExploreCourseCourseRoute = ExploreCourseCourseRouteImport.update({
  id: '/course/$course',
  path: '/course/$course',
  getParentRoute: () => ExploreRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteRouteWithChildren
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/graph': typeof GraphRoute
  '/explore/': typeof ExploreIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/explore/course/$course': typeof ExploreCourseCourseRoute
  '/explore/discipline/$discipline': typeof ExploreDisciplineDisciplineRoute
  '/explore/professor/$legacyId': typeof ExploreProfessorLegacyIdRoute
  '/schedule/calendar/advanced': typeof ScheduleCalendarAdvancedRoute
  '/schedule/calendar/basic': typeof ScheduleCalendarBasicRoute
  '/schedule/step/assign': typeof ScheduleStepAssignRoute
  '/schedule/step/completed': typeof ScheduleStepCompletedRoute
  '/schedule/step/generate': typeof ScheduleStepGenerateRoute
  '/schedule/step/mode': typeof ScheduleStepModeRoute
  '/schedule/step/options': typeof ScheduleStepOptionsRoute
  '/schedule/step/program': typeof ScheduleStepProgramRoute
  '/schedule/step/term': typeof ScheduleStepTermRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/graph': typeof GraphRoute
  '/explore': typeof ExploreIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/explore/course/$course': typeof ExploreCourseCourseRoute
  '/explore/discipline/$discipline': typeof ExploreDisciplineDisciplineRoute
  '/explore/professor/$legacyId': typeof ExploreProfessorLegacyIdRoute
  '/schedule/calendar/advanced': typeof ScheduleCalendarAdvancedRoute
  '/schedule/calendar/basic': typeof ScheduleCalendarBasicRoute
  '/schedule/step/assign': typeof ScheduleStepAssignRoute
  '/schedule/step/completed': typeof ScheduleStepCompletedRoute
  '/schedule/step/generate': typeof ScheduleStepGenerateRoute
  '/schedule/step/mode': typeof ScheduleStepModeRoute
  '/schedule/step/options': typeof ScheduleStepOptionsRoute
  '/schedule/step/program': typeof ScheduleStepProgramRoute
  '/schedule/step/term': typeof ScheduleStepTermRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteRouteWithChildren
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/graph': typeof GraphRoute
  '/explore/': typeof ExploreIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/explore/course/$course': typeof ExploreCourseCourseRoute
  '/explore/discipline/$discipline': typeof ExploreDisciplineDisciplineRoute
  '/explore/professor/$legacyId': typeof ExploreProfessorLegacyIdRoute
  '/schedule/calendar/advanced': typeof ScheduleCalendarAdvancedRoute
  '/schedule/calendar/basic': typeof ScheduleCalendarBasicRoute
  '/schedule/step/assign': typeof ScheduleStepAssignRoute
  '/schedule/step/completed': typeof ScheduleStepCompletedRoute
  '/schedule/step/generate': typeof ScheduleStepGenerateRoute
  '/schedule/step/mode': typeof ScheduleStepModeRoute
  '/schedule/step/options': typeof ScheduleStepOptionsRoute
  '/schedule/step/program': typeof ScheduleStepProgramRoute
  '/schedule/step/term': typeof ScheduleStepTermRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/schedule'
    | '/changelog'
    | '/graph'
    | '/explore/'
    | '/schedule/'
    | '/explore/course/$course'
    | '/explore/discipline/$discipline'
    | '/explore/professor/$legacyId'
    | '/schedule/calendar/advanced'
    | '/schedule/calendar/basic'
    | '/schedule/step/assign'
    | '/schedule/step/completed'
    | '/schedule/step/generate'
    | '/schedule/step/mode'
    | '/schedule/step/options'
    | '/schedule/step/program'
    | '/schedule/step/term'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/graph'
    | '/explore'
    | '/schedule'
    | '/explore/course/$course'
    | '/explore/discipline/$discipline'
    | '/explore/professor/$legacyId'
    | '/schedule/calendar/advanced'
    | '/schedule/calendar/basic'
    | '/schedule/step/assign'
    | '/schedule/step/completed'
    | '/schedule/step/generate'
    | '/schedule/step/mode'
    | '/schedule/step/options'
    | '/schedule/step/program'
    | '/schedule/step/term'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/schedule'
    | '/changelog'
    | '/graph'
    | '/explore/'
    | '/schedule/'
    | '/explore/course/$course'
    | '/explore/discipline/$discipline'
    | '/explore/professor/$legacyId'
    | '/schedule/calendar/advanced'
    | '/schedule/calendar/basic'
    | '/schedule/step/assign'
    | '/schedule/step/completed'
    | '/schedule/step/generate'
    | '/schedule/step/mode'
    | '/schedule/step/options'
    | '/schedule/step/program'
    | '/schedule/step/term'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRouteRoute: typeof ExploreRouteRouteWithChildren
  ScheduleRouteRoute: typeof ScheduleRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  GraphRoute: typeof GraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/schedule/step/term': {
      id: '/schedule/step/term'
      path: '/step/term'
      fullPath: '/schedule/step/term'
      preLoaderRoute: typeof ScheduleStepTermRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/step/program': {
      id: '/schedule/step/program'
      path: '/step/program'
      fullPath: '/schedule/step/program'
      preLoaderRoute: typeof ScheduleStepProgramRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/step/options': {
      id: '/schedule/step/options'
      path: '/step/options'
      fullPath: '/schedule/step/options'
      preLoaderRoute: typeof ScheduleStepOptionsRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/step/mode': {
      id: '/schedule/step/mode'
      path: '/step/mode'
      fullPath: '/schedule/step/mode'
      preLoaderRoute: typeof ScheduleStepModeRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/step/generate': {
      id: '/schedule/step/generate'
      path: '/step/generate'
      fullPath: '/schedule/step/generate'
      preLoaderRoute: typeof ScheduleStepGenerateRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/step/completed': {
      id: '/schedule/step/completed'
      path: '/step/completed'
      fullPath: '/schedule/step/completed'
      preLoaderRoute: typeof ScheduleStepCompletedRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/step/assign': {
      id: '/schedule/step/assign'
      path: '/step/assign'
      fullPath: '/schedule/step/assign'
      preLoaderRoute: typeof ScheduleStepAssignRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/calendar/basic': {
      id: '/schedule/calendar/basic'
      path: '/calendar/basic'
      fullPath: '/schedule/calendar/basic'
      preLoaderRoute: typeof ScheduleCalendarBasicRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/schedule/calendar/advanced': {
      id: '/schedule/calendar/advanced'
      path: '/calendar/advanced'
      fullPath: '/schedule/calendar/advanced'
      preLoaderRoute: typeof ScheduleCalendarAdvancedRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/explore/professor/$legacyId': {
      id: '/explore/professor/$legacyId'
      path: '/professor/$legacyId'
      fullPath: '/explore/professor/$legacyId'
      preLoaderRoute: typeof ExploreProfessorLegacyIdRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/discipline/$discipline': {
      id: '/explore/discipline/$discipline'
      path: '/discipline/$discipline'
      fullPath: '/explore/discipline/$discipline'
      preLoaderRoute: typeof ExploreDisciplineDisciplineRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/course/$course': {
      id: '/explore/course/$course'
      path: '/course/$course'
      fullPath: '/explore/course/$course'
      preLoaderRoute: typeof ExploreCourseCourseRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
  }
}

interface ExploreRouteRouteChildren {
  ExploreIndexRoute: typeof ExploreIndexRoute
  ExploreCourseCourseRoute: typeof ExploreCourseCourseRoute
  ExploreDisciplineDisciplineRoute: typeof ExploreDisciplineDisciplineRoute
  ExploreProfessorLegacyIdRoute: typeof ExploreProfessorLegacyIdRoute
}

const ExploreRouteRouteChildren: ExploreRouteRouteChildren = {
  ExploreIndexRoute: ExploreIndexRoute,
  ExploreCourseCourseRoute: ExploreCourseCourseRoute,
  ExploreDisciplineDisciplineRoute: ExploreDisciplineDisciplineRoute,
  ExploreProfessorLegacyIdRoute: ExploreProfessorLegacyIdRoute,
}

const ExploreRouteRouteWithChildren = ExploreRouteRoute._addFileChildren(
  ExploreRouteRouteChildren,
)

interface ScheduleRouteRouteChildren {
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  ScheduleCalendarAdvancedRoute: typeof ScheduleCalendarAdvancedRoute
  ScheduleCalendarBasicRoute: typeof ScheduleCalendarBasicRoute
  ScheduleStepAssignRoute: typeof ScheduleStepAssignRoute
  ScheduleStepCompletedRoute: typeof ScheduleStepCompletedRoute
  ScheduleStepGenerateRoute: typeof ScheduleStepGenerateRoute
  ScheduleStepModeRoute: typeof ScheduleStepModeRoute
  ScheduleStepOptionsRoute: typeof ScheduleStepOptionsRoute
  ScheduleStepProgramRoute: typeof ScheduleStepProgramRoute
  ScheduleStepTermRoute: typeof ScheduleStepTermRoute
}

const ScheduleRouteRouteChildren: ScheduleRouteRouteChildren = {
  ScheduleIndexRoute: ScheduleIndexRoute,
  ScheduleCalendarAdvancedRoute: ScheduleCalendarAdvancedRoute,
  ScheduleCalendarBasicRoute: ScheduleCalendarBasicRoute,
  ScheduleStepAssignRoute: ScheduleStepAssignRoute,
  ScheduleStepCompletedRoute: ScheduleStepCompletedRoute,
  ScheduleStepGenerateRoute: ScheduleStepGenerateRoute,
  ScheduleStepModeRoute: ScheduleStepModeRoute,
  ScheduleStepOptionsRoute: ScheduleStepOptionsRoute,
  ScheduleStepProgramRoute: ScheduleStepProgramRoute,
  ScheduleStepTermRoute: ScheduleStepTermRoute,
}

const ScheduleRouteRouteWithChildren = ScheduleRouteRoute._addFileChildren(
  ScheduleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRouteRoute: ExploreRouteRouteWithChildren,
  ScheduleRouteRoute: ScheduleRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  GraphRoute: GraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
