/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as TrendsRouteRouteImport } from './routes/trends/route'
import { Route as ScheduleRouteRouteImport } from './routes/schedule/route'
import { Route as PersonalizeRouteRouteImport } from './routes/personalize/route'
import { Route as ExploreRouteRouteImport } from './routes/explore/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendsIndexRouteImport } from './routes/trends/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as PersonalizeIndexRouteImport } from './routes/personalize/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as TrendsLeaderboardRouteImport } from './routes/trends/leaderboard'
import { Route as TrendsFeedbackRouteImport } from './routes/trends/feedback'
import { Route as TrendsDisciplinesRouteImport } from './routes/trends/disciplines'
import { Route as TrendsCoursesRouteImport } from './routes/trends/courses'
import { Route as ExploreProgramSplatRouteImport } from './routes/explore/program/$'
import { Route as ExploreDisciplineDisciplineRouteImport } from './routes/explore/discipline/$discipline'
import { Route as ExploreProfessorSlugIndexRouteImport } from './routes/explore/professor/$slug/index'
import { Route as ExploreCourseCourseIndexRouteImport } from './routes/explore/course/$course/index'
import { Route as ExploreProfessorSlugFeedbackRouteImport } from './routes/explore/professor/$slug/feedback'
import { Route as ExploreCourseCourseScheduleRouteImport } from './routes/explore/course/$course/schedule'
import { Route as ExploreCourseCourseFeedbackRouteImport } from './routes/explore/course/$course/feedback'

const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRouteRoute = TrendsRouteRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRouteRoute = ScheduleRouteRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizeRouteRoute = PersonalizeRouteRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRouteRoute = ExploreRouteRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsIndexRoute = TrendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrendsRouteRoute,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const PersonalizeIndexRoute = PersonalizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonalizeRouteRoute,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRouteRoute,
} as any)
const TrendsLeaderboardRoute = TrendsLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => TrendsRouteRoute,
} as any)
const TrendsFeedbackRoute = TrendsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => TrendsRouteRoute,
} as any)
const TrendsDisciplinesRoute = TrendsDisciplinesRouteImport.update({
  id: '/disciplines',
  path: '/disciplines',
  getParentRoute: () => TrendsRouteRoute,
} as any)
const TrendsCoursesRoute = TrendsCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TrendsRouteRoute,
} as any)
const ExploreProgramSplatRoute = ExploreProgramSplatRouteImport.update({
  id: '/program/$',
  path: '/program/$',
  getParentRoute: () => ExploreRouteRoute,
} as any)
const ExploreDisciplineDisciplineRoute =
  ExploreDisciplineDisciplineRouteImport.update({
    id: '/discipline/$discipline',
    path: '/discipline/$discipline',
    getParentRoute: () => ExploreRouteRoute,
  } as any)
const ExploreProfessorSlugIndexRoute =
  ExploreProfessorSlugIndexRouteImport.update({
    id: '/professor/$slug/',
    path: '/professor/$slug/',
    getParentRoute: () => ExploreRouteRoute,
  } as any)
const ExploreCourseCourseIndexRoute =
  ExploreCourseCourseIndexRouteImport.update({
    id: '/course/$course/',
    path: '/course/$course/',
    getParentRoute: () => ExploreRouteRoute,
  } as any)
const ExploreProfessorSlugFeedbackRoute =
  ExploreProfessorSlugFeedbackRouteImport.update({
    id: '/professor/$slug/feedback',
    path: '/professor/$slug/feedback',
    getParentRoute: () => ExploreRouteRoute,
  } as any)
const ExploreCourseCourseScheduleRoute =
  ExploreCourseCourseScheduleRouteImport.update({
    id: '/course/$course/schedule',
    path: '/course/$course/schedule',
    getParentRoute: () => ExploreRouteRoute,
  } as any)
const ExploreCourseCourseFeedbackRoute =
  ExploreCourseCourseFeedbackRouteImport.update({
    id: '/course/$course/feedback',
    path: '/course/$course/feedback',
    getParentRoute: () => ExploreRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteRouteWithChildren
  '/personalize': typeof PersonalizeRouteRouteWithChildren
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/trends': typeof TrendsRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/donate': typeof DonateRoute
  '/graph': typeof GraphRoute
  '/trends/courses': typeof TrendsCoursesRoute
  '/trends/disciplines': typeof TrendsDisciplinesRoute
  '/trends/feedback': typeof TrendsFeedbackRoute
  '/trends/leaderboard': typeof TrendsLeaderboardRoute
  '/explore/': typeof ExploreIndexRoute
  '/personalize/': typeof PersonalizeIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/trends/': typeof TrendsIndexRoute
  '/explore/discipline/$discipline': typeof ExploreDisciplineDisciplineRoute
  '/explore/program/$': typeof ExploreProgramSplatRoute
  '/explore/course/$course/feedback': typeof ExploreCourseCourseFeedbackRoute
  '/explore/course/$course/schedule': typeof ExploreCourseCourseScheduleRoute
  '/explore/professor/$slug/feedback': typeof ExploreProfessorSlugFeedbackRoute
  '/explore/course/$course/': typeof ExploreCourseCourseIndexRoute
  '/explore/professor/$slug/': typeof ExploreProfessorSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/donate': typeof DonateRoute
  '/graph': typeof GraphRoute
  '/trends/courses': typeof TrendsCoursesRoute
  '/trends/disciplines': typeof TrendsDisciplinesRoute
  '/trends/feedback': typeof TrendsFeedbackRoute
  '/trends/leaderboard': typeof TrendsLeaderboardRoute
  '/explore': typeof ExploreIndexRoute
  '/personalize': typeof PersonalizeIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/trends': typeof TrendsIndexRoute
  '/explore/discipline/$discipline': typeof ExploreDisciplineDisciplineRoute
  '/explore/program/$': typeof ExploreProgramSplatRoute
  '/explore/course/$course/feedback': typeof ExploreCourseCourseFeedbackRoute
  '/explore/course/$course/schedule': typeof ExploreCourseCourseScheduleRoute
  '/explore/professor/$slug/feedback': typeof ExploreProfessorSlugFeedbackRoute
  '/explore/course/$course': typeof ExploreCourseCourseIndexRoute
  '/explore/professor/$slug': typeof ExploreProfessorSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteRouteWithChildren
  '/personalize': typeof PersonalizeRouteRouteWithChildren
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/trends': typeof TrendsRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/donate': typeof DonateRoute
  '/graph': typeof GraphRoute
  '/trends/courses': typeof TrendsCoursesRoute
  '/trends/disciplines': typeof TrendsDisciplinesRoute
  '/trends/feedback': typeof TrendsFeedbackRoute
  '/trends/leaderboard': typeof TrendsLeaderboardRoute
  '/explore/': typeof ExploreIndexRoute
  '/personalize/': typeof PersonalizeIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/trends/': typeof TrendsIndexRoute
  '/explore/discipline/$discipline': typeof ExploreDisciplineDisciplineRoute
  '/explore/program/$': typeof ExploreProgramSplatRoute
  '/explore/course/$course/feedback': typeof ExploreCourseCourseFeedbackRoute
  '/explore/course/$course/schedule': typeof ExploreCourseCourseScheduleRoute
  '/explore/professor/$slug/feedback': typeof ExploreProfessorSlugFeedbackRoute
  '/explore/course/$course/': typeof ExploreCourseCourseIndexRoute
  '/explore/professor/$slug/': typeof ExploreProfessorSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/personalize'
    | '/schedule'
    | '/trends'
    | '/changelog'
    | '/donate'
    | '/graph'
    | '/trends/courses'
    | '/trends/disciplines'
    | '/trends/feedback'
    | '/trends/leaderboard'
    | '/explore/'
    | '/personalize/'
    | '/schedule/'
    | '/trends/'
    | '/explore/discipline/$discipline'
    | '/explore/program/$'
    | '/explore/course/$course/feedback'
    | '/explore/course/$course/schedule'
    | '/explore/professor/$slug/feedback'
    | '/explore/course/$course/'
    | '/explore/professor/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/donate'
    | '/graph'
    | '/trends/courses'
    | '/trends/disciplines'
    | '/trends/feedback'
    | '/trends/leaderboard'
    | '/explore'
    | '/personalize'
    | '/schedule'
    | '/trends'
    | '/explore/discipline/$discipline'
    | '/explore/program/$'
    | '/explore/course/$course/feedback'
    | '/explore/course/$course/schedule'
    | '/explore/professor/$slug/feedback'
    | '/explore/course/$course'
    | '/explore/professor/$slug'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/personalize'
    | '/schedule'
    | '/trends'
    | '/changelog'
    | '/donate'
    | '/graph'
    | '/trends/courses'
    | '/trends/disciplines'
    | '/trends/feedback'
    | '/trends/leaderboard'
    | '/explore/'
    | '/personalize/'
    | '/schedule/'
    | '/trends/'
    | '/explore/discipline/$discipline'
    | '/explore/program/$'
    | '/explore/course/$course/feedback'
    | '/explore/course/$course/schedule'
    | '/explore/professor/$slug/feedback'
    | '/explore/course/$course/'
    | '/explore/professor/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRouteRoute: typeof ExploreRouteRouteWithChildren
  PersonalizeRouteRoute: typeof PersonalizeRouteRouteWithChildren
  ScheduleRouteRoute: typeof ScheduleRouteRouteWithChildren
  TrendsRouteRoute: typeof TrendsRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DonateRoute: typeof DonateRoute
  GraphRoute: typeof GraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalize': {
      id: '/personalize'
      path: '/personalize'
      fullPath: '/personalize'
      preLoaderRoute: typeof PersonalizeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/': {
      id: '/trends/'
      path: '/'
      fullPath: '/trends/'
      preLoaderRoute: typeof TrendsIndexRouteImport
      parentRoute: typeof TrendsRouteRoute
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/personalize/': {
      id: '/personalize/'
      path: '/'
      fullPath: '/personalize/'
      preLoaderRoute: typeof PersonalizeIndexRouteImport
      parentRoute: typeof PersonalizeRouteRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/trends/leaderboard': {
      id: '/trends/leaderboard'
      path: '/leaderboard'
      fullPath: '/trends/leaderboard'
      preLoaderRoute: typeof TrendsLeaderboardRouteImport
      parentRoute: typeof TrendsRouteRoute
    }
    '/trends/feedback': {
      id: '/trends/feedback'
      path: '/feedback'
      fullPath: '/trends/feedback'
      preLoaderRoute: typeof TrendsFeedbackRouteImport
      parentRoute: typeof TrendsRouteRoute
    }
    '/trends/disciplines': {
      id: '/trends/disciplines'
      path: '/disciplines'
      fullPath: '/trends/disciplines'
      preLoaderRoute: typeof TrendsDisciplinesRouteImport
      parentRoute: typeof TrendsRouteRoute
    }
    '/trends/courses': {
      id: '/trends/courses'
      path: '/courses'
      fullPath: '/trends/courses'
      preLoaderRoute: typeof TrendsCoursesRouteImport
      parentRoute: typeof TrendsRouteRoute
    }
    '/explore/program/$': {
      id: '/explore/program/$'
      path: '/program/$'
      fullPath: '/explore/program/$'
      preLoaderRoute: typeof ExploreProgramSplatRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/discipline/$discipline': {
      id: '/explore/discipline/$discipline'
      path: '/discipline/$discipline'
      fullPath: '/explore/discipline/$discipline'
      preLoaderRoute: typeof ExploreDisciplineDisciplineRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/professor/$slug/': {
      id: '/explore/professor/$slug/'
      path: '/professor/$slug'
      fullPath: '/explore/professor/$slug/'
      preLoaderRoute: typeof ExploreProfessorSlugIndexRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/course/$course/': {
      id: '/explore/course/$course/'
      path: '/course/$course'
      fullPath: '/explore/course/$course/'
      preLoaderRoute: typeof ExploreCourseCourseIndexRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/professor/$slug/feedback': {
      id: '/explore/professor/$slug/feedback'
      path: '/professor/$slug/feedback'
      fullPath: '/explore/professor/$slug/feedback'
      preLoaderRoute: typeof ExploreProfessorSlugFeedbackRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/course/$course/schedule': {
      id: '/explore/course/$course/schedule'
      path: '/course/$course/schedule'
      fullPath: '/explore/course/$course/schedule'
      preLoaderRoute: typeof ExploreCourseCourseScheduleRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
    '/explore/course/$course/feedback': {
      id: '/explore/course/$course/feedback'
      path: '/course/$course/feedback'
      fullPath: '/explore/course/$course/feedback'
      preLoaderRoute: typeof ExploreCourseCourseFeedbackRouteImport
      parentRoute: typeof ExploreRouteRoute
    }
  }
}

interface ExploreRouteRouteChildren {
  ExploreIndexRoute: typeof ExploreIndexRoute
  ExploreDisciplineDisciplineRoute: typeof ExploreDisciplineDisciplineRoute
  ExploreProgramSplatRoute: typeof ExploreProgramSplatRoute
  ExploreCourseCourseFeedbackRoute: typeof ExploreCourseCourseFeedbackRoute
  ExploreCourseCourseScheduleRoute: typeof ExploreCourseCourseScheduleRoute
  ExploreProfessorSlugFeedbackRoute: typeof ExploreProfessorSlugFeedbackRoute
  ExploreCourseCourseIndexRoute: typeof ExploreCourseCourseIndexRoute
  ExploreProfessorSlugIndexRoute: typeof ExploreProfessorSlugIndexRoute
}

const ExploreRouteRouteChildren: ExploreRouteRouteChildren = {
  ExploreIndexRoute: ExploreIndexRoute,
  ExploreDisciplineDisciplineRoute: ExploreDisciplineDisciplineRoute,
  ExploreProgramSplatRoute: ExploreProgramSplatRoute,
  ExploreCourseCourseFeedbackRoute: ExploreCourseCourseFeedbackRoute,
  ExploreCourseCourseScheduleRoute: ExploreCourseCourseScheduleRoute,
  ExploreProfessorSlugFeedbackRoute: ExploreProfessorSlugFeedbackRoute,
  ExploreCourseCourseIndexRoute: ExploreCourseCourseIndexRoute,
  ExploreProfessorSlugIndexRoute: ExploreProfessorSlugIndexRoute,
}

const ExploreRouteRouteWithChildren = ExploreRouteRoute._addFileChildren(
  ExploreRouteRouteChildren,
)

interface PersonalizeRouteRouteChildren {
  PersonalizeIndexRoute: typeof PersonalizeIndexRoute
}

const PersonalizeRouteRouteChildren: PersonalizeRouteRouteChildren = {
  PersonalizeIndexRoute: PersonalizeIndexRoute,
}

const PersonalizeRouteRouteWithChildren =
  PersonalizeRouteRoute._addFileChildren(PersonalizeRouteRouteChildren)

interface ScheduleRouteRouteChildren {
  ScheduleIndexRoute: typeof ScheduleIndexRoute
}

const ScheduleRouteRouteChildren: ScheduleRouteRouteChildren = {
  ScheduleIndexRoute: ScheduleIndexRoute,
}

const ScheduleRouteRouteWithChildren = ScheduleRouteRoute._addFileChildren(
  ScheduleRouteRouteChildren,
)

interface TrendsRouteRouteChildren {
  TrendsCoursesRoute: typeof TrendsCoursesRoute
  TrendsDisciplinesRoute: typeof TrendsDisciplinesRoute
  TrendsFeedbackRoute: typeof TrendsFeedbackRoute
  TrendsLeaderboardRoute: typeof TrendsLeaderboardRoute
  TrendsIndexRoute: typeof TrendsIndexRoute
}

const TrendsRouteRouteChildren: TrendsRouteRouteChildren = {
  TrendsCoursesRoute: TrendsCoursesRoute,
  TrendsDisciplinesRoute: TrendsDisciplinesRoute,
  TrendsFeedbackRoute: TrendsFeedbackRoute,
  TrendsLeaderboardRoute: TrendsLeaderboardRoute,
  TrendsIndexRoute: TrendsIndexRoute,
}

const TrendsRouteRouteWithChildren = TrendsRouteRoute._addFileChildren(
  TrendsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRouteRoute: ExploreRouteRouteWithChildren,
  PersonalizeRouteRoute: PersonalizeRouteRouteWithChildren,
  ScheduleRouteRoute: ScheduleRouteRouteWithChildren,
  TrendsRouteRoute: TrendsRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DonateRoute: DonateRoute,
  GraphRoute: GraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
