/**
 * Build-time codegen for the data asset manifest. This module is node-only (it
 * has no runtime dependencies and is never imported by browser/worker bundles —
 * it is reached only via the `@uoplan/data/codegen` subpath from the Vite plugin
 * and the data-proto build script). It renders the generated module consumed at
 * runtime through {@link DataManifest}.
 */

/** Map of asset id (`<school>/<name>.pb`) → resolved, served URL. */
export type DataManifest = Record<string, string>;

const HEADER = `// AUTO-GENERATED by the data-manifest build. Do not edit.
// Maps each \`.pb\` asset id (its path under \`assets/data\`, i.e. \`<school>/<name>.pb\`)
// to the URL it is served from.
// A placeholder is scaffolded by \`pnpm build:data-proto\`; the real, content-
// hashed URLs are written by the web Vite build (see apps/web/vite/data-manifest-plugin.ts).
`;

/** Render the generated `dataManifest.ts` module source for a given map. */
export function renderDataManifestModule(manifest: DataManifest): string {
  const entries = Object.keys(manifest)
    .sort()
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(manifest[id])},`)
    .join("\n");
  return `${HEADER}
export const dataManifest: Record<string, string> = {
${entries}
};
`;
}
