import chalk from "chalk";
import ora from "ora";
import { Command } from "commander";
import { getSession } from "../../auth/keychain.ts";
import { buildClient } from "../../api/client.ts";
import { ENDPOINTS } from "../../api/endpoints.ts";
import { listCart } from "../../api/cart.ts";
import { submitCartAction, CART_ACTIONS } from "../../api/enrollment.ts";
import { decodePayload, addCoursesToCart, handleAuthError } from "./cart.ts";
import { snipe } from "./sniper.ts";
import { promptCourseSelection, promptEnrolMode, promptSnipeTime } from "./interactive.ts";

async function runPayload(raw: string): Promise<void> {
  let decoded: ReturnType<typeof decodePayload>;
  try {
    decoded = decodePayload(raw);
  } catch {
    console.error(
      chalk.red("Invalid payload: could not decode. Make sure you copied it correctly."),
    );
    process.exit(1);
  }

  if (decoded.courses.length === 0) {
    console.log(chalk.yellow("Payload contains no courses."));
    return;
  }

  const session = getSession();
  if (!session) {
    console.error(chalk.red("Not logged in. Run `uoplan login` first."));
    process.exit(1);
  }
  if (!session.strm) {
    console.error(chalk.red("No term selected. Run `uoplan term` first."));
    process.exit(1);
  }

  const cartUrl = session.cartUrl ?? ENDPOINTS.enrollCart;

  let client: Awaited<ReturnType<typeof buildClient>>["client"];
  const authSpinner = ora("Connecting").start();
  try {
    ({ client } = await buildClient(session));
    authSpinner.stop();
  } catch (err) {
    authSpinner.fail();
    handleAuthError(err);
  }

  const selectedCourses = await promptCourseSelection(decoded.courses);
  if (!selectedCourses) return;

  await addCoursesToCart(client, cartUrl, selectedCourses);

  const mode = await promptEnrolMode();
  if (!mode || mode === "cart") return;

  if (mode === "now") {
    const enrolSpinner = ora("Fetching cart").start();
    let items: Awaited<ReturnType<typeof listCart>>;
    try {
      items = await listCart(client, cartUrl);
      enrolSpinner.text = "Submitting enrolment";
    } catch (err) {
      enrolSpinner.fail();
      handleAuthError(err);
    }

    if (items.length === 0) {
      enrolSpinner.warn("Cart is empty — nothing to enrol.");
      return;
    }

    try {
      const { errors } = await submitCartAction(
        client,
        cartUrl,
        items.map((item) => item.bufnum),
        CART_ACTIONS.enrol,
      );
      enrolSpinner.stop();
      if (errors.length > 0) {
        for (const err of errors) console.log(`${chalk.red("error:")} ${err}`);
      } else {
        console.log(chalk.green("Done. Check uoCampus to confirm enrolment."));
      }
    } catch (err) {
      enrolSpinner.fail();
      handleAuthError(err);
    }
    return;
  }

  // mode === "snipe"
  const targetMs = await promptSnipeTime();
  if (targetMs === null) return;

  const cartSpinner = ora("Fetching cart items for snipe").start();
  let items: Awaited<ReturnType<typeof listCart>>;
  try {
    items = await listCart(client, cartUrl);
    cartSpinner.stop();
  } catch (err) {
    cartSpinner.fail();
    handleAuthError(err);
  }

  if (items.length === 0) {
    console.log(chalk.yellow("Cart is empty — nothing to snipe."));
    return;
  }

  const butnums = items.map((item) => item.bufnum);
  const { success, errors } = await snipe(client, cartUrl, butnums, targetMs);

  if (!success) {
    console.log(chalk.red("Timed out. Enrolment did not succeed."));
    for (const err of errors) console.log(`  ${chalk.red("error:")} ${err}`);
    console.log(chalk.dim("You can retry manually with: uoplan enrol"));
  } else {
    console.log(chalk.green("Done. Check uoCampus to confirm enrolment."));
  }
}

export const runCommand = new Command("run")
  .description("Execute a schedule payload generated by the uoplan web app")
  .argument("<payload>", "Base64url-encoded (optionally gzipped) protobuf payload")
  .action(async (payload: string) => {
    await runPayload(payload);
  });
