// AUTO-GENERATED by scripts/gen-icon-paths.mjs — DO NOT EDIT.
// Tabler icon path data for the SF Symbol names used by <AppIcon /> on Android/web.
// Re-run: pnpm --filter native gen:icons

export interface TablerIconPaths {
  /** SVG path `d` strings, drawn at a 24x24 viewBox. */
  paths: string[];
  /** When true the icon is fill-based (solid); otherwise stroke-based (outline). */
  filled: boolean;
}

export const ICON_PATHS: Record<string, TablerIconPaths> = {
  "arrow.right": { paths: ["M5 12l14 0", "M13 18l6 -6", "M13 6l6 6"], filled: false },
  "arrow.triangle.2.circlepath": {
    paths: ["M20 11a8.1 8.1 0 0 0 -15.5 -2m-.5 -4v4h4", "M4 13a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4"],
    filled: false,
  },
  "arrow.up.right": { paths: ["M17 7l-10 10", "M8 7l9 0l0 9"], filled: false },
  "arrow.up.right.square": {
    paths: [
      "M12 6h-6a2 2 0 0 0 -2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-6",
      "M11 13l9 -9",
      "M15 4h5v5",
    ],
    filled: false,
  },
  book: {
    paths: [
      "M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0",
      "M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0",
      "M3 6l0 13",
      "M12 6l0 13",
      "M21 6l0 13",
    ],
    filled: false,
  },
  "bubble.left.fill": {
    paths: [
      "M5.821 4.91c3.899 -2.765 9.468 -2.539 13.073 .535c3.667 3.129 4.168 8.238 1.152 11.898c-2.841 3.447 -7.965 4.583 -12.231 2.805l-.233 -.101l-4.374 .931l-.04 .006l-.035 .007h-.018l-.022 .005h-.038l-.033 .004l-.021 -.001l-.023 .001l-.033 -.003h-.035l-.022 -.004l-.022 -.002l-.035 -.007l-.034 -.005l-.016 -.004l-.024 -.005l-.049 -.016l-.024 -.005l-.011 -.005l-.022 -.007l-.045 -.02l-.03 -.012l-.011 -.006l-.014 -.006l-.031 -.018l-.045 -.024l-.016 -.011l-.037 -.026l-.04 -.027l-.002 -.004l-.013 -.009l-.043 -.04l-.025 -.02l-.006 -.007l-.056 -.062l-.013 -.014l-.011 -.014l-.039 -.056l-.014 -.019l-.005 -.01l-.042 -.073l-.007 -.012l-.004 -.008l-.007 -.012l-.014 -.038l-.02 -.042l-.004 -.016l-.004 -.01l-.017 -.061l-.007 -.018l-.002 -.015l-.005 -.019l-.005 -.033l-.008 -.042l-.002 -.031l-.003 -.01v-.016l-.004 -.054l.001 -.036l.001 -.023l.002 -.053l.004 -.025v-.019l.008 -.035l.005 -.034l.005 -.02l.004 -.02l.018 -.06l.003 -.013l1.15 -3.45l-.022 -.037c-2.21 -3.747 -1.209 -8.391 2.413 -11.119z",
    ],
    filled: true,
  },
  calendar: {
    paths: [
      "M4 7a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12",
      "M16 3v4",
      "M8 3v4",
      "M4 11h16",
      "M11 15h1",
      "M12 15v3",
    ],
    filled: false,
  },
  "calendar.badge.exclamationmark": {
    paths: [
      "M15 21h-9a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v5",
      "M16 3v4",
      "M8 3v4",
      "M4 11h16",
      "M11 15h1",
      "M12 15v3",
      "M19 16v3",
      "M19 22v.01",
    ],
    filled: false,
  },
  "calendar.badge.plus": {
    paths: [
      "M12.5 21h-6.5a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v5",
      "M16 3v4",
      "M8 3v4",
      "M4 11h16",
      "M16 19h6",
      "M19 16v6",
    ],
    filled: false,
  },
  cart: {
    paths: [
      "M4 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
      "M15 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
      "M17 17h-11v-14h-2",
      "M6 5l14 1l-1 7h-13",
    ],
    filled: false,
  },
  "cart.badge.plus": {
    paths: [
      "M4 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0",
      "M12.5 17h-6.5v-14h-2",
      "M6 5l14 1l-.86 6.017m-2.64 .983h-10.5",
      "M16 19h6",
      "M19 16v6",
    ],
    filled: false,
  },
  "chart.bar": {
    paths: [
      "M3 13a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -6",
      "M15 9a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -10",
      "M9 5a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -14",
      "M4 20h14",
    ],
    filled: false,
  },
  check: { paths: ["M5 12l5 5l10 -10"], filled: false },
  checkmark: { paths: ["M5 12l5 5l10 -10"], filled: false },
  "checkmark.circle.fill": {
    paths: [
      "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-1.293 5.953a1 1 0 0 0 -1.32 -.083l-.094 .083l-3.293 3.292l-1.293 -1.292l-.094 -.083a1 1 0 0 0 -1.403 1.403l.083 .094l2 2l.094 .083a1 1 0 0 0 1.226 0l.094 -.083l4 -4l.083 -.094a1 1 0 0 0 -.083 -1.32z",
    ],
    filled: true,
  },
  "chevron.down": { paths: ["M6 9l6 6l6 -6"], filled: false },
  "chevron.left": { paths: ["M15 6l-6 6l6 6"], filled: false },
  "chevron.left.forwardslash.chevron.right": {
    paths: ["M7 8l-4 4l4 4", "M17 8l4 4l-4 4", "M14 4l-4 16"],
    filled: false,
  },
  "chevron.right": { paths: ["M9 6l6 6l-6 6"], filled: false },
  "chevron.up": { paths: ["M6 15l6 -6l6 6"], filled: false },
  circle: { paths: ["M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"], filled: false },
  "doc.text": {
    paths: [
      "M14 3v4a1 1 0 0 0 1 1h4",
      "M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2",
      "M9 9l1 0",
      "M9 13l6 0",
      "M9 17l6 0",
    ],
    filled: false,
  },
  envelope: {
    paths: [
      "M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10",
      "M3 7l9 6l9 -6",
    ],
    filled: false,
  },
  "exclamationmark.circle": {
    paths: ["M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0", "M12 8v4", "M12 16h.01"],
    filled: false,
  },
  "exclamationmark.triangle": {
    paths: [
      "M12 9v4",
      "M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0",
      "M12 16h.01",
    ],
    filled: false,
  },
  flag: {
    paths: ["M5 5a5 5 0 0 1 7 0a5 5 0 0 0 7 0v9a5 5 0 0 1 -7 0a5 5 0 0 0 -7 0v-9", "M5 21v-7"],
    filled: false,
  },
  gearshape: {
    paths: [
      "M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065",
      "M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0",
    ],
    filled: false,
  },
  globe: {
    paths: [
      "M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0",
      "M3.6 9h16.8",
      "M3.6 15h16.8",
      "M11.5 3a17 17 0 0 0 0 18",
      "M12.5 3a17 17 0 0 1 0 18",
    ],
    filled: false,
  },
  graduationcap: {
    paths: ["M22 9l-10 -4l-10 4l10 4l10 -4v6", "M6 10.6v5.4a6 3 0 0 0 12 0v-5.4"],
    filled: false,
  },
  heart: {
    paths: ["M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572"],
    filled: false,
  },
  "heart.fill": {
    paths: [
      "M6.979 3.074a6 6 0 0 1 4.988 1.425l.037 .033l.034 -.03a6 6 0 0 1 4.733 -1.44l.246 .036a6 6 0 0 1 3.364 10.008l-.18 .185l-.048 .041l-7.45 7.379a1 1 0 0 1 -1.313 .082l-.094 -.082l-7.493 -7.422a6 6 0 0 1 3.176 -10.215z",
    ],
    filled: true,
  },
  link: {
    paths: [
      "M9 15l6 -6",
      "M11 6l.463 -.536a5 5 0 0 1 7.071 7.072l-.534 .464",
      "M13 18l-.397 .534a5.068 5.068 0 0 1 -7.127 0a4.972 4.972 0 0 1 0 -7.071l.524 -.463",
    ],
    filled: false,
  },
  "list.bullet": {
    paths: ["M9 6l11 0", "M9 12l11 0", "M9 18l11 0", "M5 6l0 .01", "M5 12l0 .01", "M5 18l0 .01"],
    filled: false,
  },
  magnifyingglass: {
    paths: ["M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0", "M21 21l-6 -6"],
    filled: false,
  },
  minus: { paths: ["M5 12l14 0"], filled: false },
  "person.crop.circle": {
    paths: [
      "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0",
      "M9 10a3 3 0 1 0 6 0a3 3 0 1 0 -6 0",
      "M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855",
    ],
    filled: false,
  },
  pin: {
    paths: [
      "M15 4.5l-4 4l-4 1.5l-1.5 1.5l7 7l1.5 -1.5l1.5 -4l4 -4",
      "M9 15l-4.5 4.5",
      "M14.5 4l5.5 5.5",
    ],
    filled: false,
  },
  plus: { paths: ["M12 5l0 14", "M5 12l14 0"], filled: false },
  "server.rack": {
    paths: [
      "M3 7a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-2",
      "M3 15a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3l0 -2",
      "M7 8l0 .01",
      "M7 16l0 .01",
      "M11 8h6",
      "M11 16h6",
    ],
    filled: false,
  },
  "slider.horizontal.3": {
    paths: [
      "M12 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
      "M4 6l8 0",
      "M16 6l4 0",
      "M6 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
      "M4 12l2 0",
      "M10 12l10 0",
      "M15 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
      "M4 18l11 0",
      "M19 18l1 0",
    ],
    filled: false,
  },
  sparkles: {
    paths: [
      "M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m0 -12a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m-7 12a6 6 0 0 1 6 -6a6 6 0 0 1 -6 -6a6 6 0 0 1 -6 6a6 6 0 0 1 6 6",
    ],
    filled: false,
  },
  "square.and.arrow.up": {
    paths: [
      "M3 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0",
      "M15 6a3 3 0 1 0 6 0a3 3 0 1 0 -6 0",
      "M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0",
      "M8.7 10.7l6.6 -3.4",
      "M8.7 13.3l6.6 3.4",
    ],
    filled: false,
  },
  "square.grid.2x2.fill": {
    paths: [
      "M9 3a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z",
      "M19 3a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z",
      "M9 13a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z",
      "M19 13a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z",
    ],
    filled: true,
  },
  "star.fill": {
    paths: [
      "M8.243 7.34l-6.38 .925l-.113 .023a1 1 0 0 0 -.44 1.684l4.622 4.499l-1.09 6.355l-.013 .11a1 1 0 0 0 1.464 .944l5.706 -3l5.693 3l.1 .046a1 1 0 0 0 1.352 -1.1l-1.091 -6.355l4.624 -4.5l.078 -.085a1 1 0 0 0 -.633 -1.62l-6.38 -.926l-2.852 -5.78a1 1 0 0 0 -1.794 0l-2.853 5.78z",
    ],
    filled: true,
  },
  "waveform.path.ecg": { paths: ["M3 12h4.5l1.5 -6l4 12l2 -9l1.5 3h4.5"], filled: false },
  xmark: { paths: ["M18 6l-12 12", "M6 6l12 12"], filled: false },
};
