import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef } from "react";
import { CalendarPage } from "../../components/calendar/CalendarPage";
import { AppDataLoader } from "../../components/shared/AppDataLoader";
import { useRepairSeedOnCalendarMount } from "../../hooks/useRepairSeedOnCalendarMount";
import {
  useActiveProgram,
  useDataset,
  useLazyData,
  useScheduleGeneration,
  useSeedNavigation,
  useTermSelection,
} from "@uoplan/store/hooks";
import { buildPageHead } from "../../lib/seo";
import { hasPersistedGeneratedSchedule } from "@uoplan/store/seedNavigation";
import { formatTermLabel } from "../../lib/term/termLabel";

export const Route = createFileRoute("/schedule/")({
  head: () => buildPageHead("schedule"),
  component: CalendarRoute,
});

function CalendarRoute() {
  useRepairSeedOnCalendarMount();

  const { ensureCourseGrades } = useLazyData();
  useEffect(() => {
    void ensureCourseGrades();
  }, [ensureCourseGrades]);

  const { generateSchedules, generateBasicSchedules, currentSchedule, generationError } =
    useScheduleGeneration();
  const program = useActiveProgram();
  const { indices, loadProgress } = useDataset();
  const { firstSeed, currentSeed } = useSeedNavigation();
  const { terms, selectedTermId } = useTermSelection();

  useEffect(() => {
    const hasTerm = terms?.some((t) => String(t.termId) === selectedTermId) ?? false;
    const termName = hasTerm && selectedTermId ? formatTermLabel(selectedTermId) : null;
    document.title = termName ? `${termName} schedule` : "Schedule";
  }, [terms, selectedTermId]);

  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (hasAutoGeneratedRef.current || !indices) return;
    // A generation has already been attempted by another path (it produced an
    // error). Mark as attempted so dismissing the error modal doesn't re-trigger
    // generation and reopen the modal.
    if (generationError !== null) {
      hasAutoGeneratedRef.current = true;
      return;
    }
    if (currentSchedule === null && hasPersistedGeneratedSchedule(firstSeed, currentSeed)) {
      hasAutoGeneratedRef.current = true;
      // Basic mode (no program selected) must use the basic-elective generation
      // path; the advanced path has no requirement courses and would error out.
      void (program === null ? generateBasicSchedules() : generateSchedules());
    }
  }, [
    indices,
    currentSchedule,
    firstSeed,
    currentSeed,
    generateSchedules,
    generateBasicSchedules,
    program,
    generationError,
  ]);

  // Keep the data loader on screen until the very first schedule resolves, so the
  // calendar doesn't flash an empty state during the initial auto-generation.
  const firstScheduleResolved = currentSchedule !== null || generationError !== null;
  const initialLoadResolvedRef = useRef(false);
  useEffect(() => {
    if (firstScheduleResolved) initialLoadResolvedRef.current = true;
  }, [firstScheduleResolved]);

  const awaitingFirstSchedule =
    !firstScheduleResolved &&
    !initialLoadResolvedRef.current &&
    indices != null &&
    hasPersistedGeneratedSchedule(firstSeed, currentSeed);

  if (awaitingFirstSchedule) {
    return <AppDataLoader progress={loadProgress} mode="generating" />;
  }

  return <CalendarPage />;
}
