import fs from "node:fs/promises";
import path from "node:path";
import * as DataProto from "@uoplan/proto/data";
import * as FeedbackProto from "@uoplan/proto/feedback";
import { toProtoIndices } from "@uoplan/core/dataTypes/indices";
import {
  CATALOGUE_DATA_DIR,
  DATA_MANIFEST_FILE,
  SCHEDULES_DATA_DIR,
  SCRAPER_DATA_DIR,
  WEB_ASSETS_DATA_DIR,
} from "../shared/paths.ts";
import { readJson } from "../shared/json.ts";
import { buildFeedbackData } from "./feedback.ts";
import { mapCatalogue } from "./catalogue.ts";
import type { CatalogueJsonInput } from "./catalogue.ts";
import { mapDisciplinesJson, mapGradesJson } from "./grades.ts";
import { mapSchedules } from "./schedules.ts";
import type { SchedulesJsonInput } from "./schedules.ts";
import { createResolverFromRegistry } from "../professors/buildRegistry.ts";
import type { ProfessorRegistryEntry } from "../professors/buildRegistry.ts";
import { PROFESSORS_FILE } from "../professors/build.ts";
import {
  buildPredictionContext,
  predictInstructorsForTerm,
} from "../schedules/predictInstructors.ts";
import type { GradesCourseInput, ScheduleFileInput } from "../schedules/predictInstructors.ts";
import { parseTermIdToNumber } from "./shared.ts";
import { normalizeTermName } from "../terms/normalize.ts";

interface RateMyProfessorInput {
  id?: string;
  legacyId?: number;
  name?: string;
  rating?: number | null;
  numRatings?: number;
}

async function writePb(filePath: string, bytes: Uint8Array): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, bytes);
}

/**
 * Ensure build:data-proto leaves behind the generated data-manifest module when
 * no Vite build has created it yet. Existing manifests are preserved so content-
 * hashed asset URLs from the web build are not clobbered.
 */
async function scaffoldDataManifest(): Promise<void> {
  if (
    await fs
      .access(DATA_MANIFEST_FILE)
      .then(() => true)
      .catch(() => false)
  ) {
    return;
  }
  const entries = (await fs.readdir(WEB_ASSETS_DATA_DIR).catch(() => [] as string[])).filter((f) =>
    f.endsWith(".pb"),
  );
  const manifest: Record<string, string> = {};
  for (const id of entries.sort()) manifest[id] = `/data/${id}`;
  const body = Object.keys(manifest)
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(manifest[id])},`)
    .join("\n");
  const source = `// AUTO-GENERATED by the data-manifest build. Do not edit.
// Maps each \`.pb\` asset id (its bare filename) to the URL it is served from.
// A placeholder is scaffolded by \`pnpm build:data-proto\`; the real, content-
// hashed URLs are written by the web Vite build (see apps/web/vite/data-manifest-plugin.ts).

export const dataManifest: Record<string, string> = {
${body}
};
`;
  await fs.mkdir(path.dirname(DATA_MANIFEST_FILE), { recursive: true });
  await fs.writeFile(DATA_MANIFEST_FILE, source);
}

function isCatalogueYearJson(name: string): boolean {
  return /^catalogue\.\d{4}\.json$/.test(name);
}

function isScheduleJson(name: string): boolean {
  return /^schedules\.\d+\.json$/.test(name);
}

export async function main(): Promise<void> {
  await fs.mkdir(WEB_ASSETS_DATA_DIR, { recursive: true });

  const catalogueEntries = await fs.readdir(CATALOGUE_DATA_DIR).catch(() => [] as string[]);
  const scheduleEntries = await fs.readdir(SCHEDULES_DATA_DIR).catch(() => [] as string[]);
  const yearCatalogues = catalogueEntries.filter(isCatalogueYearJson).sort();
  const scheduleFiles = scheduleEntries.filter(isScheduleJson).sort();

  const manifest = await readJson<{ years: number[] }>(
    path.join(CATALOGUE_DATA_DIR, "catalogue.json"),
  );
  await writePb(
    path.join(WEB_ASSETS_DATA_DIR, "catalogue.pb"),
    DataProto.CatalogueManifest.encode({
      years: manifest.years ?? [],
    }).finish(),
  );

  const terms = await readJson<{
    terms: Array<{ termId: string; name: string }>;
  }>(path.join(SCRAPER_DATA_DIR, "terms.json"));
  await writePb(
    path.join(WEB_ASSETS_DATA_DIR, "terms.pb"),
    DataProto.TermsData.encode({
      terms: (terms.terms ?? []).map((t) => ({
        termId: parseTermIdToNumber(String(t.termId ?? "")),
        name: normalizeTermName(t.name),
      })),
    }).finish(),
  );

  const indices = await readJson<{ courses: string[]; programs: string[]; disciplines?: string[] }>(
    path.join(SCRAPER_DATA_DIR, "indices.json"),
  );
  await writePb(
    path.join(WEB_ASSETS_DATA_DIR, "indices.pb"),
    DataProto.Indices.encode(
      toProtoIndices({
        courses: indices.courses ?? [],
        programs: indices.programs ?? [],
        disciplines: indices.disciplines ?? [],
      }),
    ).finish(),
  );

  const rmp = await readJson<{ resultCount?: number; professors?: RateMyProfessorInput[] }>(
    path.join(SCRAPER_DATA_DIR, "ratemyprofessors.json"),
  );
  await writePb(
    path.join(WEB_ASSETS_DATA_DIR, "ratemyprofessors.pb"),
    DataProto.RateMyProfessorsData.encode({
      resultCount: rmp.resultCount ?? 0,
      professors: (rmp.professors ?? []).map((p) => ({
        legacyId: p.legacyId,
        name: p.name ?? "",
        rating: p.rating ?? undefined,
        numRatings: p.numRatings,
      })),
    }).finish(),
  );

  const disciplinesJson = await readJson<unknown>(path.join(SCRAPER_DATA_DIR, "disciplines.json"));
  await writePb(
    path.join(WEB_ASSETS_DATA_DIR, "disciplines.pb"),
    DataProto.DisciplinesData.encode(mapDisciplinesJson(disciplinesJson)).finish(),
  );

  // Canonical professor registry (committed data/professors.json): emit the
  // dictionary and build the resolver every other dataset uses to reference a
  // professor by his registry index.
  const registry =
    (await readJson<{ professors?: ProfessorRegistryEntry[] }>(PROFESSORS_FILE).catch(() => null))
      ?.professors ?? [];
  const professorResolver = createResolverFromRegistry(registry);
  await writePb(
    path.join(WEB_ASSETS_DATA_DIR, "professors.pb"),
    DataProto.ProfessorsData.encode({
      professors: registry.map((p) => ({
        name: p.name,
        legacyIds: p.legacyIds,
        rating: p.rating,
        numRatings: p.numRatings,
        aliases: p.aliases,
      })),
    }).finish(),
  );

  for (const fileName of yearCatalogues) {
    const fullPath = path.join(CATALOGUE_DATA_DIR, fileName);
    const data = await readJson<CatalogueJsonInput>(fullPath);
    const encoded = DataProto.Catalogue.encode(mapCatalogue(data)).finish();
    await writePb(path.join(WEB_ASSETS_DATA_DIR, fileName.replace(/\.json$/, ".pb")), encoded);
  }

  const gradesJson = await readJson<unknown[]>(path.join(SCRAPER_DATA_DIR, "grades.json"));

  // Load every schedule file once so build-time instructor prediction can draw
  // candidates from all recent terms; predictions are informational only.
  const scheduleJsonByFile = new Map<string, SchedulesJsonInput>();
  for (const fileName of scheduleFiles) {
    scheduleJsonByFile.set(
      fileName,
      await readJson<SchedulesJsonInput>(path.join(SCHEDULES_DATA_DIR, fileName)),
    );
  }
  const predictionContext = buildPredictionContext({
    grades: gradesJson as GradesCourseInput[],
    scheduleFiles: [...scheduleJsonByFile.values()] as ScheduleFileInput[],
    rmp: rmp.professors ?? [],
  });

  for (const fileName of scheduleFiles) {
    const data = scheduleJsonByFile.get(fileName)!;
    const predictions = predictInstructorsForTerm(data as ScheduleFileInput, predictionContext);
    const encoded = DataProto.SchedulesData.encode(
      mapSchedules(data, predictions, professorResolver),
    ).finish();
    await writePb(path.join(WEB_ASSETS_DATA_DIR, fileName.replace(/\.json$/, ".pb")), encoded);
  }

  await writePb(
    path.join(WEB_ASSETS_DATA_DIR, "grades.pb"),
    DataProto.GradesData.encode(mapGradesJson(gradesJson, professorResolver)).finish(),
  );

  const feedback = await buildFeedbackData(professorResolver);
  if (feedback) {
    await writePb(
      path.join(WEB_ASSETS_DATA_DIR, "feedback.pb"),
      FeedbackProto.FeedbackData.encode(feedback).finish(),
    );
  }

  await scaffoldDataManifest();

  console.log(
    `Generated protobuf data: ${yearCatalogues.length} catalogue files, ${scheduleFiles.length} schedule files, grades.pb, disciplines.pb${feedback ? ", feedback.pb" : ""}`,
  );
}

void (async () => {
  try {
    await main();
  } catch (err) {
    console.error("Failed to build protobuf data artifacts.");
    console.error(err);
    process.exit(1);
  }
})();
