import { describe, expect, it } from "vitest";
import { renderDataManifestModule } from "../codegen";

describe("renderDataManifestModule", () => {
  it("renders a deterministic TypeScript module with sorted, JSON-escaped asset ids", () => {
    const source = renderDataManifestModule({
      "terms.pb": "/assets/terms.hash.pb",
      'catalogue."2026".pb': "/assets/catalogue.2026.hash.pb",
    });

    expect(source).toContain("AUTO-GENERATED by the data-manifest build");
    expect(source).toContain("export const dataManifest: Record<string, string> = {");
    expect(source.indexOf('"catalogue.\\"2026\\".pb"')).toBeLessThan(source.indexOf('"terms.pb"'));
    expect(source).toContain('  "catalogue.\\"2026\\".pb": "/assets/catalogue.2026.hash.pb",');
    expect(source).toContain('  "terms.pb": "/assets/terms.hash.pb",');
    expect(source).toMatch(/\n};\n$/);
  });
});
